# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Club-Typo
tagline:          'Ressources pour amateurs de typographie'
description:      'Regarde tout ce qu''on peut faire avec LaTeX ! Fait par <a href="https://twitter.com/jjvie" target="_blank">@jjvie</a>.'
url:              http://club-typo.fr
baseurl:          /

author:
  name:           'Jill-Jênn Vie'
  url:            https://twitter.com/jjvie

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/jilljenn/club-typo
